name: Develop branch workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  call-frontend-workflow:
    uses: ./.github/workflows/frontend-workflow.yml



